    language: cpp
compiler: gcc
dist: trusty
sudo: required
cache:
    directories:
        - apt_mingw_cache
        - $HOME/.ccache
matrix:
    include:
        - env: TYPE=style
        - os: linux
        - env: TARGET_OS=win32
        - env: TARGET_OS=win64
        - os: osx
          osx_image: xcode8.3
install: ${TRAVIS_BUILD_DIR}/.travis/install.sh
script: ${TRAVIS_BUILD_DIR}/.travis/script.sh
after_script: ${TRAVIS_BUILD_DIR}/.travis/after_script.sh
deploy:
    provider: releases
    api_key:
        secure: "v9ED6nJBEB6cSCN1uMyi4CqnEM6Iiqm0upAXd2QOOjgdZA5g1D+hVlDm4TA1FVyZLBgYnOKDwJI5tI8TgEIWEfRxsqBfI6X2mEXqXhNopxTkcnTKGz102VwdMquDn8wE7SInkvcNsM2ZTKMjyf+SxonK3O7H6AWqNHFbJa/DZFx5rzdHfxh1GdVP2OwzCmvEM+knz+UoKhia/2D9zQBw8Vn7lQDLBErGeAckQx6vx0/LcG4tluyfPdyv2GbF/KaunIXVd4PNG68Pfcilioktq/BgUlVXffLKNPK6opDkTErjZ8eY34IYYACun5H8QX9qdBbj1LT+Ce53R6hMMiJ5qdqPWinQtsOOJblCu8/AV3Pv1ASU6x5hdcjYm4vv1eWBKzydCyaBk2iSgFysCjhcMwiKuHjmjB4kJiT8QMzo9sOrxtz4t/JWVz99H+5N1SYOg8fQSUx8SKqMyl7s0zY+TkT0i94JHKVYbZS0yV/BnIXVlUissUgDBwOOkh9LoJy1qJHip3I33ZIRrpH4uXANNljyrPgjiOoeA8ekWWb7yqh0mCcknJ2DihPwwA9jSScyjC96PbZ/OJiHFpTL/cuoMJ5Y6tkW1ay7VFpxoldSPXHGxjQg8hqsHNCyQHapSqm4A6xm5nHPT2FiVfBt855k9anDE5iY5A+56nbA+54C5+Q="
    file_glob: true
    file: 
        - lmms-*.AppImage
        - lmms-*.dmg
        - lmms-*win*.exe
    skip_cleanup: true
    repo: LmmsBot/LmmsPRsAtrifacts
